Add dev deployment workflow
GSA/site-scanning-engine pull request #130
Opened 2021-12-23 15:52 UTC by wesley-dean-gsa

https://github.com/GSA/site-scanning/issues/136

This PR adds a workflow to deploy to the dev environment.

Triggered upon merge to main, this workflow will allow us to test code in a non-production environment before deploying to prod.

2021-12-23 16:17 UTC, wesley-dean-gsa commented
I've converted this PR to a draft as it is not ready to be merged.

2022-01-10 19:29 UTC, wesley-dean-gsa commented
Previously, the `cloudgov-deploy.sh` script pushed with a manifest file named for the environment (e.g., `manifest-dev.yml`) or whatever the user passed to it.  That is, if the user passed `dev` (e.g., `cloudgov-deploy.sh dev`), then it tried to use a manifest filename of `dev` (not `manifest-dev.yml`) which failed.

The script will now accept an environment or a filename.  If the filename exists, it'll be used.  If it does NOT exist, it's assumed that what was passed was the name of the environment (space) and a manifest filename will be constructed from the name of the environment.

The fallback is `${project_root}/manifest-dev.yml` (i.e., the manifest filename for the dev environment) as we don't want to accidentally damage the prod environment.

2022-01-14 16:19 UTC, danielnaab requested changes
I have a couple of minor nits, but awesome work!

2022-01-14 16:19 UTC, danielnaab commented on .github/workflows/deploy.yml
> +      - name: deploy producer
You can remove producer from the prod deploy also.

2022-01-14 16:19 UTC, danielnaab commented on .github/workflows/dev.yml
> +          # scale to two instances with 4G scratch disk and 2G memory each and force deploy
btw I like your suggestion of upping the timeout to 180 seconds, to avoid the need for this step. But if we ended up doing that, it could wait for follow up work.

2022-01-14 16:19 UTC, danielnaab commented on cloudgov-deploy.sh
> +  npm run build cli
you can remove the cli build step - `build:all` includes it.

2022-01-14 16:51 UTC, wesley-dean-gsa commented on cloudgov-deploy.sh
> +  npm run build cli
pushed

2022-01-14 17:05 UTC, wesley-dean-gsa commented on .github/workflows/dev.yml
> +          # scale to two instances with 4G scratch disk and 2G memory each and force deploy
agreed

2022-01-14 17:06 UTC, danielnaab approved these changes
:shipit:

2022-01-14 17:30 UTC, merged