177 deploy documentation
GSA/site-scanning-engine pull request #156
Opened 2022-02-22 18:06 UTC by wesley-dean-gsa

Updated documentation to include deployment instructions

# resolves GSA/site-scanning#177

2022-02-23 23:49 UTC, danielnaab requested changes
Awesome, very thorough! I just noted a couple typos.

2022-02-23 23:49 UTC, danielnaab commented on docs/deployment.md
> +with serveral `<add_a_key_here>` indicators.  These need to be
```suggestion
with several `<add_a_key_here>` indicators.  These need to be
```

2022-02-23 23:49 UTC, danielnaab commented on docs/deployment.md
> +so that updates are pushed to the correct service.
Since this document is so thorough, perhaps a note on how to target here would be good.

2022-02-28 18:06 UTC, wesley-dean-gsa commented on docs/deployment.md
> +so that updates are pushed to the correct service.
updates pushed

2022-02-28 20:31 UTC, danielnaab approved these changes

2022-02-28 20:31 UTC, merged